### ISSUE TITLE
Is this an official mirror?

### ISSUE THREAD

**Issue by brettwooldridge** [milesibastos/jTDS#1]
Is this an official github mirror of jTDS?

**Comment by milesibastos** [comment]
Hi,
Unfortunately not!
This is a fork where I add support to SQL LocalDB.
I think the project a little freeze at the version 1.3.1 but the links are:
jTDS homepage: http://jtds.sourceforge.net/
SourceForge project info: http://sourceforge.net/projects/jtds/

Welcome to contribut if u have any interest.
